### ISSUE TITLE
Error exporting bibtex

### ISSUE THREAD

**Issue by corycaean** [callumalpass/obsidian-biblib#5]
I'm getting an error exporting bibtex, but I can export as .json and .md fine. Here's the error in the console:

![Image](https://github.com/user-attachments/assets/601e6659-49cd-4ce5-9b41-098dd9161337)

Here's an example of one of my notes imported from Zotero:

![Image](https://github.com/user-attachments/assets/b931a75b-8791-4519-99b4-6ce0b8dfd443)

I can see that something's up with some of the fields, but I can't know what.

**Comment by callumalpass** [comment]
Thanks for reporting this issue! I've identified and fixed the problem with BibTeX exports when encountering empty date arrays.

The error occurred when Citation.js tried to process citation data that contained empty date arrays in the issued field (or other date fields). Specifically, when notes had a structure like:

```yaml
  issued:
    date-parts:
      - []
```

This structure is sometimes created when importing from Zotero, and Citation.js wasn't able to handle these empty arrays properly when converting to BibTeX format.

I've implemented a solution that preprocesses the citation data before sending it to the Citation.js library. The fix:

  1. Identifies all date-related fields (issued, accessed, etc.) with empty date-parts arrays
  2. Removes these problematic fields from the export data (while preserving your original note data)
  3. Allows the BibTeX export to proceed without errors

This approach is better than modifying the import process because it handles cases where empty date fields might come from multiple sources, and it doesn't alter your original data.

Thanks again for reporting this! Please let me know if you're still encountering problems after updating BibLib to 1.6.2.

**Comment by corycaean** [comment]
Hey thanks for the quick response. On 1.8.3 and still getting an error:

![Image](https://github.com/user-attachments/assets/ac68de76-3f6e-4229-a41f-91bfc385c3d0)

**Comment by corycaean** [comment]
Maybe deseves a seperate thread, but I'm also having this issue updating .json:

![Image](https://github.com/user-attachments/assets/f8c513b0-f4aa-488e-b0c7-4a4aea8d1c8c)

Works fine if I delete the file and run it again, but I'm guessing the preferred behavior is update and replace.

**Comment by Misters-Wise** [comment]
Why don't the imported zotero notes include the files ?
